
class ConfigFields:
    
    # Dicionário de status_text baseados nos códigos de status
    FIELD_STATUS_CODE = {
        100: 'Continuar',
        101: 'Mudando Protocolos',
        200: 'OK',
        201: 'Criado',
        202: 'Aceito',
        203: 'Informações Não Autorizadas',
        204: 'Sem Conteúdo',
        205: 'Resetar Conteúdo',
        206: 'Conteúdo Parcial',
        300: 'Múltiplas Escolhas',
        301: 'Movido Permanentemente',
        302: 'Encontrado',
        303: 'Veja Outros',
        304: 'Não Modificado',
        305: 'Use Proxy',
        307: 'Redirecionamento Temporário',
        400: 'Solicitação Inválida',
        401: 'Não Autorizado',
        402: 'Pagamento Necessário',
        403: 'Proibido',
        404: 'Não Encontrado',
        405: 'Método Não Permitido',
        406: 'Não Aceitável',
        407: 'Autenticação de Proxy Necessária',
        408: 'Tempo de Solicitação Esgotado',
        409: 'Conflito',
        410: 'Gone',
        411: 'Comprimento Necessário',
        412: 'Pré-condição Falhou',
        413: 'Entidade de Solicitação Muito Grande',
        414: 'URI de Solicitação Muito Longa',
        415: 'Tipo de Mídia Não Suportado',
        416: 'Intervalo Não Satisfatório',
        417: 'Falha na Expectativa',
        500: 'Erro Interno do Servidor',
        501: 'Não Implementado',
        502: 'Bad Gateway',
        503: 'Serviço Indisponível',
        504: 'Gateway Timeout',
        505: 'Versão HTTP Não Suportada'
    }
    

    FIELD_VALIDATE_PYDANTIC = {
        "value is not a valid string"                           : "O valor deve ser uma string válida",
        "string does not match regex"                           : "A string não corresponde à expressão regular",
        "value is not a valid integer"                          : "O valor deve ser um número inteiro válido",
        "value is not a valid float"                            : "O valor deve ser um número decimal válido",
        "value is not a valid boolean"                          : "O valor deve ser um booleano válido",
        "field required"                                        : "Campo obrigatório",
        "value is not a valid dict"                             : "O valor deve ser um dicionário válido",
        "value is not a valid list"                             : "O valor deve ser uma lista válida",
        "value is not a valid tuple"                            : "O valor deve ser uma tupla válida",
        "value is not a valid set"                              : "O valor deve ser um conjunto válido",
        "value is not a valid bytes"                            : "O valor deve ser um bytes válido",
        "string does not match the expected length"             : "A string não tem o comprimento esperado",
        "ensure this value has at least {limit_value} items"    : "Certifique-se de que este valor tenha pelo menos {limit_value} itens",
        "ensure this value has at most {limit_value} items"     : "Certifique-se de que este valor tenha no máximo {limit_value} itens",
        "value is not a valid email address"                    : "O valor deve ser um endereço de e-mail válido",
        "value is not a valid URL"                              : "O valor deve ser uma URL válida",
        "value is not a valid UUID"                             : "O valor deve ser um UUID válido",
        "value is not a valid date"                             : "O valor deve ser uma data válida",
        "value is not a valid datetime"                         : "O valor deve ser uma data e hora válidas",
        "value is not a valid time"                             : "O valor deve ser uma hora válida",
        "value is not a valid timedelta"                        : "O valor deve ser um timedelta válido",
        "value is not a valid IPv4 address"                     : "O valor deve ser um endereço IPv4 válido",
        "value is not a valid IPv6 address"                     : "O valor deve ser um endereço IPv6 válido",
        "value is not a valid IP address"                       : "O valor deve ser um endereço IP válido",
        "value is not a valid currency"                         : "O valor deve ser uma moeda válida",
        "value is not a valid decimal"                          : "O valor deve ser um decimal válido",
        "value is not a valid color"                            : "O valor deve ser uma cor válida",
        "value is not a valid file path"                        : "O valor deve ser um caminho de arquivo válido",
        "value is not a valid file name"                        : "O valor deve ser um nome de arquivo válido",
        "input should be a valid string"                        : "A entrada deve ser uma string válida",
        "input should be a valid integer"                       : "A entrada deve ser um número inteiro válido",
        "input should be a valid float"                         : "A entrada deve ser um número decimal válido",
        "input should be a valid boolean"                       : "A entrada deve ser um booleano válido",
        "input should be a valid list"                          : "A entrada deve ser uma lista válida",
        "input should be a valid dict"                          : "A entrada deve ser um dicionário válido",
        "value is not a valid enumeration member"               : "O valor não é um membro válido da enumeração",
        "value is not a valid date time"                        : "O valor não é uma data e hora válida",
        "invalid literal for int() with base 10"                : "Literal inválido para int() com base 10",
        "not a valid path"                                      : "Não é um caminho válido",
        "not a valid instance of {class_name}"                  : "Não é uma instância válida de {class_name}",
    }